name: Deploy Admin Portal to Azure

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Admin
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # IMPORTANT: You must create a GitHub Secret named AZURE_STATIC_WEB_APPS_API_TOKEN_ADMIN
          # and paste your Azure Static Web App deployment token into it.
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ADMIN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./cs-antiques-admin" # Points to your admin folder
          api_location: ""
          output_location: "dist"
